Adapter precice 3.1 with 3D suppoint and "point load"
precice/fenicsx-adapter pull request #26
Opened 2024-07-16 20:56 UTC by efirvida

2024-07-26 17:43 UTC, efirvida commented
I finally made it work, at least the perpendicular flap tutorial, To do it I added a `LinearDiscreteProblem` that puts the load directly on the DoFs and also maintains the code clean. 

![flap-x-displacement-tip](https://github.com/user-attachments/assets/3dc7d6aa-443f-47dc-907c-090efb958ec3)


I added two more examples the turek-heron, and a turbine-tower, right now I'm running them to see what happens. I'm having problems by running the turbine-tower in parallel from the OpenFOAM side, but I don't know how to diagnose what happen

2024-08-05 14:53 UTC, IshaanDesai reviewed
Thank you for your contribution and apologies for the delay in reviewing. Even if the total number of new files is large, as a first step I looked at the adapter files, so the folder `fenicsxprecice`. I see that you have broadly stuck to the existing adapter class structure, by having a `Config` class, an `Adapter` class, and a class to manage the state for checkpointing. To me it seems like this could have potentially been accommodated in the existing adapter structure. What was the reason to completely discard the existing adapter and write a new one?

Contents of the file `fenicsxprecice/solvers.py` is related to the numerical solvers. Such code typically goes in the application files, as it is not directly related to coupling.

Apart from the adapter files, there are a lot of files related to different simulation setups. Ideally such simulation setups are added to the [precice/tutorials](https://github.com/precice/tutorials) repository, rather than the adapter repository. Once we start to converge on the adapter contribution, we can move the case files to the tutorials repository.

2024-08-05 17:40 UTC, efirvida commented
@IshaanDesai thanks for your quick review. Yes, I use the original adapter structure, because first I tried to use the original on my FSI by doing the small modifications. As I'm new on preCICE and DOLFINx, I began to modify the code in place to do some reverse engineering, until I reached good results, and I removed a lot of code that I didn't understand to keep my version as clean as possible with the minimum needs to perform an FSI, as you can see the API on this version is a lot simpler than the original. 

I know that I put a lot of tutorials that do not belong here, as de solver.py, but I think it is easier to have all things together in one place to test/review before moving/merge and put all in the right place.

The main part of the Adapter are the methods:

```
interpolation_points_in_vector_space
interface_dof
```
the first return the DOFs and coordinates of the interface. and then is easy to use the `interface_dof` to read and write data from the evaluated Function. I tried to add another tutorial on heat transfer but I've not time to do it to see if this approach also works for this kind of solution. Also, the Turek-FSI isn't working well I think because this is a nonlinear problem and I use a linear solver.

2024-08-08 12:20 UTC, IshaanDesai commented
> Yes, I use the original adapter structure, because first I tried to use the original on my FSI by doing the small modifications. As I'm new on preCICE and DOLFINx, I began to modify the code in place to do some reverse engineering, until I reached good results, and I removed a lot of code that I didn't understand to keep my version as clean as possible with the minimum needs to perform an FSI, as you can see the API on this version is a lot simpler than the original.

I understand how your reached the state you have, and that it serves the purpose of doing FSI simulations. But the original structure is intended to be for generic use and was also designed rigorously for legacy FEniCS. I am tending towards keeping the old structure and accommodating your improvements in it. Did you encounter any fundamental design problems while trying to incorporate your implementation in the current adapter? If yes, we can improve the design.

> I know that I put a lot of tutorials that do not belong here, as de solver.py, but I think it is easier to have all things together in one place to test/review before moving/merge and put all in the right place. But OK I did some cleaning

This is perfectly fine for now, but just something to do at the end, just before merging.

> I tried to add another tutorial on heat transfer but I've not time to do it to see if this approach also works for this kind of solution.

This would be very interesting to know. If this can be done, we could potentially just move to the new design.

> Also, the Turek-FSI isn't working well I think because this is a nonlinear problem and I use a linear solver.

This is a known problem.

I would suggest the following next steps:

1. I can help you to try to incorporate your implementation into the current adapter design. This way we can keep the design but you can also do FSI simulations.
2. Move your simulation setups to the tutorials repository one by one.
3. If possible, add some tests for the new functionality.

What do you think? I will, of course, assist to a large degree here.

2024-08-08 12:47 UTC, efirvida commented
I can try to adapt my implementation into the current adapter, but for this, I would need your help, I don't remember the problems in the main implementation.

I think that the main cut-off is on the `initialize` method where I believe the `write_object` is not needed here, or at least I didn't understand its function. Maybe due to the simple implementation of the read/write data methods, that I put the data directly on the Function.

And the same for the `create/update_coupling_expression` that I think we don't need here, at least for FSI.

Right now this version has a problem working in parallel, and I'm working on it right now, the I could try to start mergin with the current implementation. Notice that the current implementation also is for preCICE < 3, and this implementation not, so here some method changes its names and parameters.

2024-08-08 14:28 UTC, IshaanDesai commented
> I can try to adapt my implementation into the current adapter, but for this, I would need your help, I don't remember the problems in the main implementation.

I can and will definitely help here.

I see that you extract the data from the function directly at the time of reading and writing. I will check how this would work with the original implementation.

Handling FEniCS Expressions was part of the original design because many times Expressions were used on the user-side. We can rethink this now.

> Right now this version has a problem working in parallel, and I'm working on it right now, the I could try to start mergin with the current implementation.

I saw the Discourse post about the issue with parallel runs. Let me try to answer there, so as to not clutter this pull request too much. Thanks for agreeing to merging with the current implementation :smile: I know it feels like taking a step backwards, but in the long run we would benefit from the original design decisions.

> Notice that the current implementation also is for preCICE < 3, and this implementation not, so here some method changes its names and parameters.

Thanks for pointing this out :+1:

2024-08-09 17:47 UTC, efirvida commented
I accidentally overwrote my last commit, but I believe it's not a significant issue. I modified the adapter using the current class reference to simplify the merging process.

In the current implementation, the read and write methods are much simpler because preCICE v3 does not differentiate between vectors and scalars, using the same function for both. I also removed some checks that I didn't fully understand, and I'm not certain if they were necessary.

```
        assert (self._coupling_type is CouplingMode.UNI_DIRECTIONAL_READ_COUPLING or
                CouplingMode.BI_DIRECTIONAL_COUPLING) 
```

As I mention in my last post, I'm porting the adapter to preCICEv3 so some methods change, now we have:

- `requires_initial_data` instead of `is_action_required`
- `requires_reading_checkpoint` instead of `action_read_iteration_checkpoint`
- `requires_writing_checkpoint` instead of `action_write_iteration_checkpoint`

I also added some new properties:

- `dt`: This property captures the participant's time step (dt), so it's no longer necessary to specify it separately in our problem setup.
- `interface_dof`: This is the most important property, enabling us to read and write interface data. You can think of it as analogous to the PointSource in the legacy FEniCS version.
- `interface_coordinates`: This property is mainly for debugging purposes. It allows us to visualize the interface interpolation points by saving them as a CSV file, which can then be plotted.

So the API change a little bit due to this new properties, and the change of the preCICE version.

Also in the `initialize` method I left the `write_object` param just to maintain compatibility, but my current implementation don't need it. And also I remove all the check on this methods because I didn't understand, and I'm not sure if they were necessary.

FinallyI include the flap tutorial again with this modification, jus to show how we can use it.

2024-08-09 17:56 UTC, efirvida commented
Also I manage to add a working heat transfer tutorial, in [this commit](https://github.com/efirvida/fenicsx-adapter/commit/d6c5320dddece98460a1b24a7670523c6b884f05#diff-e1b5c6d7ff07eb6e9b3518ee669e964174430d22c918fd2cf564378219943a64) of my main branch (which is not aligned right now with this last version). The tutorial  runs until the end and change data between participants, but as I'm not an expert in heat transfer I'm sure that there are things wrong there on the FEniCSx side implementation, but it's a starting point

2024-08-16 10:56 UTC, IshaanDesai requested changes
Thank you for refactoring your adapter design into the old design. I see now that most things in the old design are rendered unnecessary. The write function in the initialization can be removed as it no longer serves a purpose. I have some last suggestions, which I have written as comments. Once these are incorporated, we can finalize this pull request. Before merging, we should move the simulation setups to the tutorials repository. I can quickly port these once testing is done.

2024-08-16 10:56 UTC, IshaanDesai commented on  LICENSE
> +Library.
Lets not change the license file. Can you please keep the original file?

2024-08-16 10:56 UTC, IshaanDesai commented on .gitattributes
> -fenicsxprecice/_version.py export-subst
Same as the license file.

2024-08-16 10:56 UTC, IshaanDesai commented on .github/workflows/build-and-test.yml
We should keep the build and test CI, hence we need this file, and the Action to pass.

2024-08-16 10:56 UTC, IshaanDesai commented on .github/workflows/build-docker.yml
We need to keep this CI.

2024-08-16 10:56 UTC, IshaanDesai commented on .github/workflows/check-links.yml
Same as other CI related files. Let us keep this file to keep the check.

2024-08-16 10:56 UTC, IshaanDesai commented on .github/workflows/check-markdown.yml
Same as other CI related files. Let us keep this file to keep the check.

2024-08-16 10:56 UTC, IshaanDesai commented on .github/workflows/check-pep8.yml
Same as other CI related files. Let us keep this file to keep the check.

2024-08-16 10:56 UTC, IshaanDesai commented on .github/workflows/run-tutorials.yml
Lets keep this file. It is okay if the tutorial CI fails for now. Eventually when we move the case to the precice/tutorials repository, the CI will pass again.

2024-08-16 10:56 UTC, IshaanDesai commented on CHANGELOG.md
> +* Forked initial version of this adapter from [`precice/fenics-adapter@v1.2.0`](https://github.com/precice/fenics-adapter/releases/tag/v1.2.0).
Not sure what the change is here. Please add a separate CHANGELOG entry describing the changes introduced in this pull request.

2024-08-16 10:56 UTC, IshaanDesai commented on README.md
> +* [preCICE v3](https://github.com/precice/precice/wiki)
```suggestion
* [preCICE](https://precice.org/)
```

2024-08-16 10:56 UTC, IshaanDesai commented on README.md
> +
We no longer need scipy?

2024-08-16 10:56 UTC, IshaanDesai commented on README.md
> +2024:  [Eduardo Firvida](https://github.com/efirvida) updated the adapter to a minimal working version (https://github.com/precice/fenicsx-adapter/pull/26) with FSI and 3D support for preCICEv3. In t
```suggestion
2024:  [Eduardo Firvida](https://github.com/efirvida) updated the adapter to support 3D FSI simulations and also made the adapter compatible with preCICE version 3 (https://github.com/precice/fenicsx-adapter/pull/26).
```

2024-08-16 10:56 UTC, IshaanDesai commented on docs/ReleaseGuide.md
We need to keep the documentation.

2024-08-16 10:56 UTC, IshaanDesai commented on fenicsxprecice/__init__.py
> +
Is this reordering necessary?

2024-08-16 10:56 UTC, IshaanDesai commented on fenicsxprecice/config.py
> +"""This is the configuration module of fenicsxadapter
Let us keep the original formatting to maintain readability.

2024-08-16 10:56 UTC, IshaanDesai commented on fenicsxprecice/config.py
> +    """Handles reading of config. parameters of the fenicsxadapter based on JSON
Same as above.

2024-08-16 10:56 UTC, IshaanDesai commented on fenicsxprecice/config.py
> +        """Reads JSON adapter configuration file and saves the data to the respective instance attributes.
Same as above.

2024-08-16 10:56 UTC, IshaanDesai commented on fenicsxprecice/fenicsxprecice.py
> -"""
Let us keep these first documentation lines.

2024-08-16 10:56 UTC, IshaanDesai commented on fenicsxprecice/fenicsxprecice.py
> +class Dimensions(NamedTuple):
Can you please add a short comment block stating what this class is doing?

2024-08-16 10:56 UTC, IshaanDesai commented on fenicsxprecice/fenicsxprecice.py
> +    """This adapter class provides an interface to the preCICE v3 coupling library for setting up a
```suggestion
    """
    This adapter class provides an interface to the preCICE v3 coupling library for setting up a
```

2024-08-16 10:56 UTC, IshaanDesai commented on fenicsxprecice/fenicsxprecice.py
> +        """Constructor of Adapter class.
```suggestion
        """
        Constructor of Adapter class.
```

2024-08-16 10:56 UTC, IshaanDesai commented on fenicsxprecice/fenicsxprecice.py
> +        self._config = Config(adapter_config_filename)
No need for this reordering.

2024-08-16 10:56 UTC, IshaanDesai commented on fenicsxprecice/fenicsxprecice.py
> +        """Determine interpolation points in the vector space.
```suggestion
        """
        Determine interpolation points in the vector space.
```

2024-08-16 10:56 UTC, IshaanDesai commented on fenicsxprecice/fenicsxprecice.py
> +        """Read data from preCICE.
```suggestion
        """
        Read data from preCICE.
```

2024-08-16 10:56 UTC, IshaanDesai commented on fenicsxprecice/fenicsxprecice.py
> +        np.ndarray
```suggestion
        read_data : np.ndarray
```

2024-08-16 10:56 UTC, IshaanDesai commented on fenicsxprecice/fenicsxprecice.py
> +            The incoming data containing nodal data ordered according to _fenicsx_vertices
```suggestion
            Data containing nodal data ordered according to _fenicsx_vertices
```

2024-08-16 10:56 UTC, IshaanDesai commented on fenicsxprecice/fenicsxprecice.py
> +        # https://precice.org/couple-your-code-porting-v2-3.html#add-relativereadtime-for-all-read-data-calls
```suggestion
```

2024-08-16 10:56 UTC, IshaanDesai commented on fenicsxprecice/fenicsxprecice.py
> +        """Writes data to preCICE. Depending on the dimensions of the simulation.
```suggestion
        """
        Writes data to preCICE. Depending on the dimensions of the simulation.
```

2024-08-16 10:56 UTC, IshaanDesai commented on fenicsxprecice/fenicsxprecice.py
> +        """Initializes the coupling and sets up the mesh where coupling happens in preCICE.
```suggestion
        """
        Initializes the coupling and sets up the mesh where coupling happens in preCICE.
```

2024-08-16 10:56 UTC, IshaanDesai commented on fenicsxprecice/fenicsxprecice.py
> +        coupling_subdomain : List
```suggestion
        coupling_subdomain : list
```

2024-08-16 10:56 UTC, IshaanDesai commented on fenicsxprecice/fenicsxprecice.py
> +        """Defines an object of class SolverState which stores the current states of the variable and the time stamp."""
```suggestion
        """
        Defines an object of class SolverState which stores the current states of the variable and the time stamp.
        """
```

2024-08-16 10:56 UTC, IshaanDesai commented on fenicsxprecice/fenicsxprecice.py
> +        """Resets the FEniCSx participant state to the state of the stored checkpoint.
```suggestion
        """
        Resets the FEniCSx participant state to the state of the stored checkpoint.
```

2024-08-16 10:56 UTC, IshaanDesai commented on tests/README.md
Lets try to preserve the testing infrastructure as much as possible. I understand that tests related to old functionality are no longer relevant, but modifying existing tests to test the new functionality would be really helpful in catching potential bugs.

2024-08-16 13:14 UTC, BenjaminRodenberg reviewed
Thanks a lot for all the work and the updates! I don't want to interfere too much here. Just two small comments on versioneer-related files. I would try to not mix these changes into the PR because it's not really related.

For some background: We are using versioneer in this repository to synchronize git-tags and the version numbers used in the `setup.py` respectively returned by `fenicsxadapter.__version__`.

2024-08-16 13:14 UTC, BenjaminRodenberg commented on versioneer.py
Can you revert the changes in this file? I think no changes should be necessary here.

2024-08-16 13:14 UTC, BenjaminRodenberg commented on fenicsxprecice/_version.py
This file is generated by versioneer. Please revert the changes.

2024-11-26 10:03 UTC, BenjaminRodenberg commented
To make this PR a bit easier to review and manage I reverted some changes in [fc02757](https://github.com/precice/fenicsx-adapter/pull/26/commits/fc027578cf8f5d8c5f200cdef617f80a680842c3). This should reduce the diff to some degree. @efirvida: If this interferes with your work, feel free to simply revert that commit (`git revert fc02757`). We can also use a different branch than `develop` to continue working on this PR.

I think we should generally try to factor some things out from this PR. Otherwise it is just too big. Some points that are part of this PR which we could factor out are type checks with mypy and some documentation changes. We should also try to fix the testing here in this PR in order to make sure we do not break anything. Additionally, this would also reduce the diff (currently there are many deletions due to the removal of the testing).

2024-11-28 16:42 UTC, steffenger commented
https://github.com/efirvida/fenicsx-adapter/blob/develop/fenicsxprecice/fenicsxprecice.py#L84 This version of the adapter only supports surface coupling now, right? It think it should be possible to make it more general with an additional argument in the initialization of the adapter. 
best regards

2025-05-06 08:08 UTC, BenjaminRodenberg commented
fyi: I added this PR to the milestone for the upcoming release (see https://github.com/precice/fenicsx-adapter/milestone/1). I think we should either close or merge this issue. In any case we should try to make sure we do not loose critical functionality provided in this PR in the process.

2026-03-30 08:47 UTC, IshaanDesai commented
Closing this PR because the adapter has advanced significantly, and merging it is no longer viable.

2026-03-30 08:47 UTC, closed without merging